// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckMusicDir(arg1:string):Promise<boolean>;

export function DownloadLyric(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetLyric(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<main.LyricResult>;

export function GetMusicFiles(arg1:string):Promise<Array<main.MusicFile>>;

export function SelectMusicFolder():Promise<string>;

export function StartAudioServer():Promise<string>;

export function StopAudioServer():Promise<void>;
