// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMusicDir(arg1) {
  return window['go']['main']['App']['CheckMusicDir'](arg1);
}

export function DownloadLyric(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadLyric'](arg1, arg2, arg3, arg4);
}

export function GetLyric(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetLyric'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetMusicFiles(arg1) {
  return window['go']['main']['App']['GetMusicFiles'](arg1);
}

export function SelectMusicFolder() {
  return window['go']['main']['App']['SelectMusicFolder']();
}

export function StartAudioServer() {
  return window['go']['main']['App']['StartAudioServer']();
}

export function StopAudioServer() {
  return window['go']['main']['App']['StopAudioServer']();
}
