// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMusicDir(arg1) {
  return window['go']['main']['App']['CheckMusicDir'](arg1);
}

export function ClearThemeFiles() {
  return window['go']['main']['App']['ClearThemeFiles']();
}

export function ClearThumbnails() {
  return window['go']['main']['App']['ClearThumbnails']();
}

export function DownloadLyric(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadLyric'](arg1, arg2, arg3, arg4);
}

export function DownloadLyricFromNetEase(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadLyricFromNetEase'](arg1, arg2, arg3);
}

export function FetchCoverFromNetEase(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchCoverFromNetEase'](arg1, arg2, arg3);
}

export function GetBgImage() {
  return window['go']['main']['App']['GetBgImage']();
}

export function GetCover(arg1, arg2) {
  return window['go']['main']['App']['GetCover'](arg1, arg2);
}

export function GetLyric(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetLyric'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetMediaFiles(arg1) {
  return window['go']['main']['App']['GetMediaFiles'](arg1);
}

export function GetMusicFiles(arg1) {
  return window['go']['main']['App']['GetMusicFiles'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStartTime() {
  return window['go']['main']['App']['GetStartTime']();
}

export function LogMessage(arg1) {
  return window['go']['main']['App']['LogMessage'](arg1);
}

export function OpenCacheFolder() {
  return window['go']['main']['App']['OpenCacheFolder']();
}

export function SaveBgImage(arg1) {
  return window['go']['main']['App']['SaveBgImage'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectMusicFolder() {
  return window['go']['main']['App']['SelectMusicFolder']();
}

export function StartAudioServer() {
  return window['go']['main']['App']['StartAudioServer']();
}

export function StopAudioServer() {
  return window['go']['main']['App']['StopAudioServer']();
}
