// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckMusicDir(arg1:string):Promise<boolean>;

export function ClearThemeFiles():Promise<void>;

export function ClearThumbnails():Promise<void>;

export function DownloadLyric(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function FetchCoverFromNetEase(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetBgImage():Promise<boolean>;

export function GetCover(arg1:string,arg2:string):Promise<string>;

export function GetLyric(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<main.LyricResult>;

export function GetMediaFiles(arg1:string):Promise<main.MediaFilesResult>;

export function GetMusicFiles(arg1:string):Promise<Array<main.MusicFile>>;

export function GetSettings():Promise<string>;

export function GetStartTime():Promise<number>;

export function LogMessage(arg1:string):Promise<void>;

export function SaveBgImage(arg1:string):Promise<boolean>;

export function SaveSettings(arg1:string):Promise<void>;

export function SelectMusicFolder():Promise<string>;

export function StartAudioServer():Promise<string>;

export function StopAudioServer():Promise<void>;
